import Header from '@/components/Header';
import Footer from '@/components/Footer';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Beyond The Bench",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* Favicon */}
        <link rel="icon" href="/favicon.png" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />

        {/* Fonts */}
        <link rel="stylesheet" href="/fonts/stylesheet.css" />

        {/* Styles */}
        <link rel="stylesheet" href="/css/bootstrap.css" />
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body>
        <div id="smooth-wrapper">
          <div id="smooth-content">
              <div id="app">
                  <Header />
                  
                  <main>{children}</main>
                  
                  <Footer />
              </div>
          </div>
        </div>

        {/* Scripts */}
        <script src="/js/jquery.js" defer></script>
        <script src="/js/bootstrap.js" defer></script>
        <script src="/js/popper.js" defer></script>
        <script src="/js/gsap.js" defer></script>
        <script src="/js/ScrollTrigger.js" defer></script>
        <script src="/js/ScrollSmoother.js" defer></script>
        <script src="/js/custom.js" defer></script>
      </body>
    </html>
  );
}